kind: Deployment
apiVersion: apps/v1
metadata:
  name: dummy-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-workload
  template:
    metadata:
      labels:
        app: dummy-workload
    spec:
      containers:
      - name: dummy-workload
        image: registry.cern.ch/rvasek/dummy-fuse-csi:latest
        imagePullPolicy: Always
        command: ["/bin/dummy-fuse-workload"]
        args: [
          "--file", "/mnt/dummy-file.txt",
          # "--exit-on-error",
          # "--keep-open",
        ]
        volumeMounts:
        - name: mypvc
          mountPath: /mnt
      volumes:
      - name: mypvc
        persistentVolumeClaim: 
          claimName: dummy-fuse-pvc
          readOnly: false
