apiVersion: v1
kind: Pod
metadata:
  name: dummy-fuse-pod
spec:
  containers:
  - name: dummy-workload
    image: rvasek/dummy-fuse-csi:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/dummy-fuse-workload"]
    args: ["--file", "/mnt/dummy-file.txt"]
    volumeMounts:
    - name: mypvc
      mountPath: /mnt
  volumes:
  - name: mypvc
    persistentVolumeClaim: 
      claimName: dummy-fuse-pvc
      readOnly: false
