apiVersion: v1
kind: PersistentVolume
metadata:
  name: dummy-fuse-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  csi:
    driver: dummy-fuse-csi.cern.ch
    volumeHandle: dummy-fuse-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-fuse-pvc
spec:
  accessModes:
   - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: dummy-fuse-pv
  storageClassName: ""
