kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dummy-fuse-csi.fullname" . }}
  labels:
    app: {{ include "dummy-fuse-csi.name" . }}
    chart: {{ include "dummy-fuse-csi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
