csi:
  plugin:
    name: dummy-fuse-csi
    image: registry.cern.ch/rvasek/dummy-fuse-csi:latest

    # Attempt to restore FUSE mounts. Doesn't work.
    restoreMounts: true

  registrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.2

# Override the default app name using nameOverride
# nameOverride: some-other-name

