csi:
  plugin:
    name: dummy-fuse-csi
    image: rvasek/dummy-fuse-csi:latest

    # Attempt to restore FUSE mounts. Doesn't work.
    restoreMounts: false

    # Attempt to restore FUSE mounts using dummy-fuse-reconciler.
    useMountReconciler: true

  registrar:
    image: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0

# Override the default app name using nameOverride
# nameOverride: some-other-name

